# Generated by Django 6.0.3 on 2026-04-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablagrupo',
            name='empatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablagrupo',
            name='ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablagrupo',
            name='goles_contra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablagrupo',
            name='goles_favor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablagrupo',
            name='jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablagrupo',
            name='perdidos',
            field=models.IntegerField(default=0),
        ),
    ]
