# Generated by Django 6.0.3 on 2026-04-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_tablagrupo_empatados_tablagrupo_ganados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoff',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playoff',
            name='ronda',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playoff',
            name='equipo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoff1', to='partidos.equipo'),
        ),
        migrations.AlterField(
            model_name='playoff',
            name='equipo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoff2', to='partidos.equipo'),
        ),
    ]
